name: build avr
on:
  push:
    paths:
      - "avr/"
      - ".github/workflows/build_avr.yml"
      - "Dockerfile"

jobs:
  build_avr:
    strategy:
      matrix:
        example_dir: ["blink", "timemeas", "togglebutton", "sleep_pci", "states", "ws2812b", "moodlight", "pwm", "hot_wire", "choreo"]
    name: Build AVR examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t uc-lab .
      - name: Build example
        run: cd avr && docker run --rm -v $(pwd):/code uc-lab /bin/bash -c "cd src/${{ matrix.example_dir }} && make hex"
