name: build rpico
on:
  push:
    paths:
      - "rpico/"
      - ".github/workflows/build_rpico.yml"
      - "Dockerfile"

jobs:
  build_pico:
    strategy:
      matrix:
        pico_board: ["pico", "pico_w", "pico2", "pico2_w", "waveshare_rp2350_zero"]
    name: Build Pico
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t uc-lab .
      - name: Build project
        run: cd rpico && docker run --rm -v $(pwd):/code uc-lab /bin/bash ./build.bash ${{ matrix.pico_board }}
